name = "qr-contact-genius2"
account_id = "03a8844ed6814af33b14f6394f04ff77"
workers_dev = true

# Route pour le Worker en production
route = "https://cardinterclosing.corentin-rollandpro.workers.dev"

main = "./worker.js"
