// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bayeilpmvqdhrirbqxgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJheWVpbHBtdnFkaHJpcmJxeGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0Njk3OTYsImV4cCI6MjA1MjA0NTc5Nn0.HIbp8c6pSxSGlh6929kDM-nh1HPa8ozwENze9G4UAO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);